
var pages = [
"https://klikjenar.blogspot.com/2019/06/manfaat-susu-kedelai-bagi-tubuh.html",
"https://klikjenar.blogspot.com/2019/06/manfaat-labu-siam-untuk-kesehatan-tubuh.html",
"https://klikjenar.blogspot.com/2019/07/cara-menghilangkan-lemak-di-perut.html",
"https://klikjenar.blogspot.com/2019/07/bahaya-makan-mie-instan-bagi-tubuh.html",
"https://klikjenar.blogspot.com/2019/07/5-cara-sumber-menghasilkan-uang-dari.html",
"https://klikjenar.blogspot.com/2019/07/tips-membuat-anak-pintar-cerdas-dan.html",
"https://klikjenar.blogspot.com/2019/07/cara-membuat-obat-amandel-alami-yang.html",
"https://klikjenar.blogspot.com/2019/07/bagi-yang-ingin-cepat-hamil-ini.html",
"https://klikjenar.blogspot.com/2019/07/jarang-diketahui-inilah-8-cara-menjaga.html",
"https://klikjenar.blogspot.com/2019/07/ini-alasan-egy-maulana-vikri-lebih.html",
"https://klikjenar.blogspot.com/2019/07/8-film-korea-yang-lucu-dan-bikin-baper.html",
"https://klikjenar.blogspot.com/2019/07/aplikasi-download-lagu-terampuh-dan.html",
"https://klikjenar.blogspot.com/2019/07/4-website-terjemahan-bahasa-inggris.html",
"https://klikjenar.blogspot.com/2019/07/drama-korea-terbaik-2019-romance-yang.html",
"https://klikjenar.blogspot.com/2019/07/model-trendy-baju-batik-wanita-islami.html",
"https://klikjenar.blogspot.com/2019/08/selain-enak-makanan-ini-bisa-dijadikan.html",
"https://klikjenar.blogspot.com/2019/08/tips-membuat-interior-mobil-agar.html",
"https://klikjenar.blogspot.com/2019/08/ini-kisaran-biayanya-modifikasi-motor.html",
"https://klikjenar.blogspot.com/2019/08/resmi-dikenalkan-arema-takafumi.html",
"https://klikjenar.blogspot.com/2019/08/masyarakat-kaltim-antusias-terkait.html",
"https://klikjenar.blogspot.com/2019/08/50-tips-ampuh-agar-suami-disayang-istri.html",
"https://klikjenar.blogspot.com/2019/08/cerita-lucu-supir-kaget-yang-bikin.html",
"https://klikjenar.blogspot.com/2019/08/cerita-humor-mencegah-kematian.html",
"https://klikjenar.blogspot.com/2019/08/cerita-kocak-seekor-katak-yang.html",
"https://klikjenar.blogspot.com/2019/08/6-manfaat-tersembunyi-sayuran-pahit.html",
"https://klikjenar.blogspot.com/2019/08/ibu-kota-pindah-ahok-bukan-karena.html",
"https://klikjenar.blogspot.com/2019/08/inspirasi-penuh-makna-sebagai.html",
"https://klikjenar.blogspot.com/2019/08/lebih-cantik-dan-menggemaskan-setelah.html",
"https://klikjenar.blogspot.com/2019/08/vivo-nex-3-punya-layar-air-terjun-dan.html",
"https://klikjenar.blogspot.com/2020/03/terlukanya-hati-istri-putuslah-rezeki.html",
"https://klikjenar.blogspot.com/2020/03/cari-pengganti-baru-itu-mungkin-mudah.html",
"https://klikjenar.blogspot.com/2020/03/air-mata-adalah-doa-disaat-kamu-tak.html",
"https://klikjenar.blogspot.com/2020/03/cara-mencegah-menularnya-virus-corona.html",
"https://klikjenar.blogspot.com/2020/04/pemerintah-sudah-keluarkan-aturan.html",
"https://klikjenar.blogspot.com/2020/04/pemberian-thr-karyawan-sesuai-dengan.html",
"https://klikjenar.blogspot.com/2020/04/2-tips-menjaga-kesehatan-tubuh-agar.html",
"https://klikjenar.blogspot.com/2020/06/funny-laugh.html",
"https://klikjenar.blogspot.com/2020/06/funny-tiktok-cute-girl.html",
"https://klikjenar.blogspot.com/2020/06/sushant-singh-rajput-bollywood-star.html",
"https://klikjenar.blogspot.com/2020/06/hank-williams-jrs-daughter-killed-in.html",
"https://klikjenar.blogspot.com/2020/06/black-in-white-coats-how-alabamas-black.html",
"https://klikjenar.blogspot.com/2020/06/da-criticizes-atlanta-police-killing-of.html",
"https://klikjenar.blogspot.com/2020/06/birmingham-sees-new-high-in-coronavirus.html",
"https://klikjenar.blogspot.com/2020/06/kay-ivey-is-not-your-mee-maw-what.html",
"https://klikjenar.blogspot.com/2020/06/historic-day-for-bubba-wallace-pushes.html",
"https://klikjenar.blogspot.com/2020/07/stream-juice-wrlds-posthumous-album.html",
"https://klikjenar.blogspot.com/2020/07/slain-montgomery-teen-was-attacked-with.html",
"https://klikjenar.blogspot.com/2020/10/pilihlah-laki-laki-yang-bisa-mencintai.html",
"https://klikjenar.blogspot.com/2020/10/lakukan-5-cara-ini-agar-tidak-mudah.html",
"https://klikjenar.blogspot.com/2020/10/khasiat-buah-mengkudu-bagi-kesehatan.html",
"https://klikjenar.blogspot.com/2020/10/5-kesalahan-saat-bertengkar-dengan.html",
"https://klikjenar.blogspot.com/2020/10/tips-jitu-jika-kamu-dijauhi-teman.html",
"https://klikjenar.blogspot.com/2020/10/cara-merawat-wajah-tanpa-skincare-agar.html",



];
function randomPage() {
return pages[Math.round(Math.random() * (pages.length - 1,2,3))];
}
location.href= randomPage();
